//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChupaChupa.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChupaChupa.Service.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add category: This category already exists..
        /// </summary>
        internal static string AddCategoryAlreadyOwned {
            get {
                return ResourceManager.GetString("AddCategoryAlreadyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add category: A technical error with database occured..
        /// </summary>
        internal static string AddCategoryDatabaseErrror {
            get {
                return ResourceManager.GetString("AddCategoryDatabaseErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add category: Category name is empty.
        /// </summary>
        internal static string AddCategoryEmptyName {
            get {
                return ResourceManager.GetString("AddCategoryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new category: Name must not exceed 64 characters..
        /// </summary>
        internal static string AddCategoryInvalidProperty {
            get {
                return ResourceManager.GetString("AddCategoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add category: User was not found in database..
        /// </summary>
        internal static string AddCategoryUserUnknown {
            get {
                return ResourceManager.GetString("AddCategoryUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: The channel is already part of another category..
        /// </summary>
        internal static string AddRssChannelAlreadyAddedCategory {
            get {
                return ResourceManager.GetString("AddRssChannelAlreadyAddedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: Rss channel is already.
        /// </summary>
        internal static string AddRssChannelAlreadyExist {
            get {
                return ResourceManager.GetString("AddRssChannelAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: User doesn&apos;t have requested category.
        /// </summary>
        internal static string AddRssChannelCategoryNotOwned {
            get {
                return ResourceManager.GetString("AddRssChannelCategoryNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: A technical error with database occured..
        /// </summary>
        internal static string AddRssChannelDatabaseError {
            get {
                return ResourceManager.GetString("AddRssChannelDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: Category name is empty..
        /// </summary>
        internal static string AddRssChannelEmptyCategory {
            get {
                return ResourceManager.GetString("AddRssChannelEmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: Url link is empty..
        /// </summary>
        internal static string AddRssChannelEmptyLink {
            get {
                return ResourceManager.GetString("AddRssChannelEmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add channel: The channel doesn&apos;t match the rss specification..
        /// </summary>
        internal static string AddRssChannelInvalidChannel {
            get {
                return ResourceManager.GetString("AddRssChannelInvalidChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rss channel: User was not found in database.
        /// </summary>
        internal static string AddRssChannelUserUnknown {
            get {
                return ResourceManager.GetString("AddRssChannelUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A technical error occured. Please contact the administrators of the application at fakeadmin@fakeadmin.com.
        /// </summary>
        internal static string AuthTechnicalError {
            get {
                return ResourceManager.GetString("AuthTechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password: A technical error with database occured. Please try again later..
        /// </summary>
        internal static string ChangePasswordDatabaseError {
            get {
                return ResourceManager.GetString("ChangePasswordDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password: New password is empty..
        /// </summary>
        internal static string ChangePasswordEmptyCredential {
            get {
                return ResourceManager.GetString("ChangePasswordEmptyCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password: Password must not exceed 255 characters..
        /// </summary>
        internal static string ChangePasswordInvalidProperty {
            get {
                return ResourceManager.GetString("ChangePasswordInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password: .
        /// </summary>
        internal static string ChangePasswordUnable {
            get {
                return ResourceManager.GetString("ChangePasswordUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password: User was not found in database..
        /// </summary>
        internal static string ChangePasswordUserUnknown {
            get {
                return ResourceManager.GetString("ChangePasswordUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new account: Account already exist. Please choose another login..
        /// </summary>
        internal static string CreateAccountAlreadyExisting {
            get {
                return ResourceManager.GetString("CreateAccountAlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new account: There was an error with database..
        /// </summary>
        internal static string CreateAccountDatabaseError {
            get {
                return ResourceManager.GetString("CreateAccountDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new account: Login or password is empty..
        /// </summary>
        internal static string CreateAccountEmptyCredentials {
            get {
                return ResourceManager.GetString("CreateAccountEmptyCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create account: Login and password must not exceed 255 characters..
        /// </summary>
        internal static string CreateAccountInvalidProperties {
            get {
                return ResourceManager.GetString("CreateAccountInvalidProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new account: Login or password is null..
        /// </summary>
        internal static string CreateAccountNullCredentials {
            get {
                return ResourceManager.GetString("CreateAccountNullCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop category: A technical error with database occured..
        /// </summary>
        internal static string DropCategoryDatabaseError {
            get {
                return ResourceManager.GetString("DropCategoryDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop category: Category name is empty.
        /// </summary>
        internal static string DropCategoryEmptyName {
            get {
                return ResourceManager.GetString("DropCategoryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop category: User was not found in database..
        /// </summary>
        internal static string DropCategoryUserUnknown {
            get {
                return ResourceManager.GetString("DropCategoryUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop rss channel: User doesn&apos;t have requested category.
        /// </summary>
        internal static string DropRssChannelCategoryNotOwned {
            get {
                return ResourceManager.GetString("DropRssChannelCategoryNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop rss channel: A technical error with database occured..
        /// </summary>
        internal static string DropRssChannelDatabaseError {
            get {
                return ResourceManager.GetString("DropRssChannelDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop channel: Channel is not owned by user..
        /// </summary>
        internal static string DropRssChannelNotOwned {
            get {
                return ResourceManager.GetString("DropRssChannelNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to drop rss channel: User was not found in database.
        /// </summary>
        internal static string DropRssChannelUserUnknown {
            get {
                return ResourceManager.GetString("DropRssChannelUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get category: User doesn&apos;t have requested category..
        /// </summary>
        internal static string GetCategoryUnknwonCategory {
            get {
                return ResourceManager.GetString("GetCategoryUnknwonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get categories: User was not found in database..
        /// </summary>
        internal static string GetCategoryUserUnknwon {
            get {
                return ResourceManager.GetString("GetCategoryUserUnknwon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get rss channels for category: User doesn&apos;t have requested category.
        /// </summary>
        internal static string GetRssChannelCategoryNotOwned {
            get {
                return ResourceManager.GetString("GetRssChannelCategoryNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get rss channel: Channel does not exist in database..
        /// </summary>
        internal static string GetRssChannelNotExisting {
            get {
                return ResourceManager.GetString("GetRssChannelNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get rss channels: User was not found in database..
        /// </summary>
        internal static string GetRssChannelUserUnknown {
            get {
                return ResourceManager.GetString("GetRssChannelUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get items: User does not have any category.
        /// </summary>
        internal static string GetRssItemCategoryNoCategory {
            get {
                return ResourceManager.GetString("GetRssItemCategoryNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get items: User does not have requested category..
        /// </summary>
        internal static string GetRssItemCategoryNotOwned {
            get {
                return ResourceManager.GetString("GetRssItemCategoryNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get items: User was not found in database..
        /// </summary>
        internal static string GetRssItemCategoryUnknownUser {
            get {
                return ResourceManager.GetString("GetRssItemCategoryUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get items: Channel doesn&apos;t exist in database..
        /// </summary>
        internal static string GetRssItemChannelNotExisting {
            get {
                return ResourceManager.GetString("GetRssItemChannelNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get items: User was not found in database. .
        /// </summary>
        internal static string GetRssItemChannelUnknownUser {
            get {
                return ResourceManager.GetString("GetRssItemChannelUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get item: Item doesn&apos;t exist in database..
        /// </summary>
        internal static string GetRssItemNotExisting {
            get {
                return ResourceManager.GetString("GetRssItemNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get item: User was not found in database..
        /// </summary>
        internal static string GetRssItemUnknownUser {
            get {
                return ResourceManager.GetString("GetRssItemUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is null..
        /// </summary>
        internal static string InvalidNullCredentials {
            get {
                return ResourceManager.GetString("InvalidNullCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: A technical error with database occured..
        /// </summary>
        internal static string MoveRssChannelDatabaseError {
            get {
                return ResourceManager.GetString("MoveRssChannelDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: New category doesn&apos;t exist..
        /// </summary>
        internal static string MoveRssChannelNewCategoryNotExist {
            get {
                return ResourceManager.GetString("MoveRssChannelNewCategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: User doesn&apos;t have any category..
        /// </summary>
        internal static string MoveRssChannelNoCategory {
            get {
                return ResourceManager.GetString("MoveRssChannelNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: Channel is not owned by user..
        /// </summary>
        internal static string MoveRssChannelNotOwnedByUser {
            get {
                return ResourceManager.GetString("MoveRssChannelNotOwnedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: Old category doesn&apos;t exist..
        /// </summary>
        internal static string MoveRssChannelOldCategoryNotExist {
            get {
                return ResourceManager.GetString("MoveRssChannelOldCategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move rss channel: User was not found in database..
        /// </summary>
        internal static string MoveRssChannelUserUnknown {
            get {
                return ResourceManager.GetString("MoveRssChannelUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: A category with the same name already exists.
        /// </summary>
        internal static string RenameCategoryAlreadyExist {
            get {
                return ResourceManager.GetString("RenameCategoryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: User doesn&apos;t have requested category..
        /// </summary>
        internal static string RenameCategoryCategoryNotOwned {
            get {
                return ResourceManager.GetString("RenameCategoryCategoryNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: A technical error with database occured..
        /// </summary>
        internal static string RenameCategoryDatabaseError {
            get {
                return ResourceManager.GetString("RenameCategoryDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: Category name is empty..
        /// </summary>
        internal static string RenameCategoryEmptyName {
            get {
                return ResourceManager.GetString("RenameCategoryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: Category name must not exceed 64 characters..
        /// </summary>
        internal static string RenameCategoryInvalidProperty {
            get {
                return ResourceManager.GetString("RenameCategoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename category: User was not found in database..
        /// </summary>
        internal static string RenameCategoryUnknownUser {
            get {
                return ResourceManager.GetString("RenameCategoryUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as read: A technical error with database occured..
        /// </summary>
        internal static string SetChannelReadDatabaseError {
            get {
                return ResourceManager.GetString("SetChannelReadDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as read: User have no categories..
        /// </summary>
        internal static string SetChannelReadNoCategory {
            get {
                return ResourceManager.GetString("SetChannelReadNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as read: Channel not owned by user..
        /// </summary>
        internal static string SetChannelReadNotOwned {
            get {
                return ResourceManager.GetString("SetChannelReadNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as read: User was not found in database..
        /// </summary>
        internal static string SetChannelReadUnknownUser {
            get {
                return ResourceManager.GetString("SetChannelReadUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as unread: A technical error with dabatase occured..
        /// </summary>
        internal static string SetChannelUnreadDatabaseError {
            get {
                return ResourceManager.GetString("SetChannelUnreadDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as unread: User does not have any categories..
        /// </summary>
        internal static string SetChannelUnreadNoCategory {
            get {
                return ResourceManager.GetString("SetChannelUnreadNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as unread: User does not own the channel..
        /// </summary>
        internal static string SetChannelUnreadNotOwned {
            get {
                return ResourceManager.GetString("SetChannelUnreadNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set channel as unread: User was not found in database..
        /// </summary>
        internal static string SetChannelUnreadUnknownUser {
            get {
                return ResourceManager.GetString("SetChannelUnreadUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbale to set item as read: A technical error with database occured..
        /// </summary>
        internal static string SetItemReadDatabaseError {
            get {
                return ResourceManager.GetString("SetItemReadDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set item as read: Item does not exist..
        /// </summary>
        internal static string SetItemReadNotExist {
            get {
                return ResourceManager.GetString("SetItemReadNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set item as read: User was not found in database..
        /// </summary>
        internal static string SetItemReadUnknownUser {
            get {
                return ResourceManager.GetString("SetItemReadUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set item as unread: A technical error with database occured..
        /// </summary>
        internal static string SetItemUnreadDatabaseError {
            get {
                return ResourceManager.GetString("SetItemUnreadDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set item as unread: User does not have any read items..
        /// </summary>
        internal static string SetItemUnreadNoItem {
            get {
                return ResourceManager.GetString("SetItemUnreadNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set item as unread: User was not found in database..
        /// </summary>
        internal static string SetItemUnreadUnknownUser {
            get {
                return ResourceManager.GetString("SetItemUnreadUnknownUser", resourceCulture);
            }
        }
    }
}
